### PR TITLE
WIP: Remove external state

### PR DESCRIPTION
**Pull request by aedrax**
This removes the external state behavior and allows a user to just make a function. However, a state will still be needed for running multiple coroutines of the same function. I'm hoping this inspires somebody to help me think of a way to do that, but leave the default case of not needing to create an external state.

### CODE REVIEW

**Comment by naasking** [comment]
I don't think there's a way to go from static state to async functions with first-class parameters, but it is possible to go the other way by defining a new macro async_static or async_begin_static that declares the static roughly as you do here. Something like:

    #define async_static static struct async _async_state = { ASYNC_INIT }; async_begin(_async_state)

The state still has to be dereferenced via the implicit local for the other macros, but the idea basically matches your PR for static async functions. I wouldn't merge your PR as-is since I think the default should encourage the programmer to manage the state explicitly rather than introduce implicit state, but I might consider merging this extra macro.

**Comment by aedrax** [comment]
I actually like what you've done with this other macro, as it cleans up the usage and fixes the state issue :)

**Comment by aedrax** [comment]
Though I'd love to find a way to allow arguments to be passed to the coroutines, maybe utilizing variadic arguments. What are your thoughts?

**Comment by naasking** [comment]
The main problem that remains is that it lets you pass in different parameters across different async calls, which may be inconsistent. For instance, you might call an async function foo(1, 'c') the first time, and then foo(10, 'a') the second time, which is technically not correct since you're changing the function's internal state without it knowing (parameters should be captured as internal state).

This is why the canonical design requires all function state to be lifted to a struct. I don't see a way around this without going all-in on a more expensive setjmp/longjmp design that captures a full continuation. That's been done in other libraries if that's what you're looking for, but it's outside the scope of what I was trying to achieve with this.

**Comment by aedrax** [comment]
Great points, I'm closing this PR but have another one utilizing your suggested macro addition :)

**Pull request closed without merging**
