### PR TITLE
Added async_sleep method to be used with await

### PR DESCRIPTION
**Pull request by shanecb**

### CODE REVIEW

**Comment by shanecb** [comment]
Sorry, didn't mean to create a real PR for this. I meant to do it in my fork.

**Comment by shanecb** [comment]
I was trying to implement a sleep method that's specific to a coroutine, and this works, but I doubt it's best approach, so if you have advice I'd appreciate any input. My C isn't very good.

**Comment by naasking** [comment]
Hey Shane, I might implement it something more like this, which is fully inline and you only have to perform the multiply once and then it's just a simple comparison:

`#define async_sleep(duration) *time = clock() + CLOCKS_PER_SEC * (duration); await(clock() >= *time)`

There's more of an overflow danger, but my use case for these kinds of header abstractions is typically embedded systems where I have to handle clock overflow anyway.

As for other suggestions, you might want to define async_state as a proper struct and use pointers to that rather than increasing the number of local pointers. Something like:

> struct async_state{ unsigned _async_k; clock_t _time; };
> #define async_state struct async_state _async
> #define async_begin(k) strut async_state \*_async = &(k)->_async; switch(\*_async->_async_k) { default:

Not a big deal for just one additional field, but if you plan to add more features it's easier to scale this way. I'm also [playing with a time-based abstraction](https://github.com/naasking/embedded/blob/master/task.h) that goes a little further than what you have here. I haven't tested it at all yet as I'm still massaging the interface, but you may find some ideas in there.

**Comment by shanecb** [comment]
Hey, thanks for responding! That's really helpful advice. I had wanted to make the `async_sleep(duration)` method a conditional expression that could be used with the `await(cond)` method because in python's asyncio the async sleep looks like: `await asyncio.sleep(x)`, which is why I created the helper function `_check_timer(...)` (because C doesn't have lambda functions and I needed the function to set the timer if it wasn't set yet). But I just implemented it like you suggested and I think I like how it looks at the call site better than the python asyncio way, plus it is nice not having the helper method.

Yeah I'm working on embedded systems too, it looks like the task scheduling framework you're working on will be really nice. Thanks again for responding, I feel inspired to get better at C now.

**Pull request closed without merging**
